# Generated by Django 2.1.3 on 2018-11-12 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0012_auto_20181111_2018"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="dept",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="info.Dept"
            ),
        ),
    ]
