# Generated by Django 5.0.6 on 2024-06-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0018_alter_assign_id_alter_assigntime_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(default="2024-05-01"),
        ),
    ]
