# Generated by Django 5.0.6 on 2024-07-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0019_alter_attendance_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assigntime",
            name="period",
            field=models.CharField(
                choices=[
                    ("8:30 - 9:45", "8:30 - 9:45"),
                    ("9:45 - 10:45", "9:45 - 10:45"),
                    ("11:10 - 12:10", "11:10 - 12:10"),
                    ("12:10 - 1:10", "12:10 - 1:10"),
                    ("1:50 - 2:40", "1:50 - 2:40"),
                    ("2:40 - 3:30", "2:40 - 3:30"),
                ],
                default="11:00 - 11:50",
                max_length=50,
            ),
        ),
    ]
